name: zotero-snap
base: core18 # the base snap is the execution environment for this snap
version: 5.0.80
summary: Zotero Standalone
description: |
  Zotero Standalone

grade: devel
confinement: strict
architectures: [amd64]

parts:
  icon:
    plugin: dump
    source: snap/local
  zotero:
    plugin: dump
    source: https://www.zotero.org/download/client/dl?channel=release&platform=linux-x86_64&version=5.0.80
    source-type: tar
    stage-packages:
      - libxt6
      - libdbus-glib-1-2
      - libgtk2.0-0

apps:
  zotero-snap:
    extensions: [ gnome-3-28 ]
    command: zotero
    desktop: zotero-launch.desktop
    plugs:
      - system-observe
      - hostname-control
      - network-bind
      - network-observe
      - browser-support
      - mount-observe
      - firewall-control
      - home
      - removable-media
